import raw from "../data/generated/github.json";

/**
 * Typed accessor for the snapshot generated by `npm run sync`
 * (scripts/sync-github.mjs). The site reads live GitHub data through
 * this module and falls back to curated values where the API has no data.
 */

export type GithubProfile = {
  name?: string | null;
  login?: string | null;
  bio?: string | null;
  avatarUrl?: string | null;
  location?: string | null;
  hireable?: boolean | null;
  twitterUsername?: string | null;
  htmlUrl?: string | null;
};

export type GithubRepo = {
  name: string;
  description?: string | null;
  htmlUrl?: string | null;
  homepage?: string | null;
  language?: string | null;
  topics?: string[];
  pushedAt?: string | null;
};

export type GithubLanguageStat = {
  language: string;
  percent: number;
};

export type GithubData = {
  fetchedAt?: string;
  profile?: GithubProfile;
  repos?: GithubRepo[];
  repoLanguages?: GithubLanguageStat[];
};

const data = raw as unknown as GithubData;

export const github = {
  fetchedAt: data.fetchedAt ?? "",
  profile: data.profile ?? {},
  repos: data.repos ?? [],
  repoLanguages: data.repoLanguages ?? [],

  findRepo(name: string): GithubRepo | undefined {
    return this.repos.find((repo) => repo.name === name);
  },
};

export type LiveProfile = {
  name: string | null;
  avatarUrl: string | null;
  hireable: boolean | null;
  location: string | null;
};

const LIVE_CACHE_KEY = "github-live-profile";
const LIVE_CACHE_TTL_MS = 15 * 60 * 1000;

function readLiveCache(): LiveProfile | null {
  try {
    const item = window.localStorage.getItem(LIVE_CACHE_KEY);
    if (!item) return null;
    const parsed = JSON.parse(item) as { fetchedAt: number; data: LiveProfile };
    if (Date.now() - parsed.fetchedAt > LIVE_CACHE_TTL_MS) return null;
    return parsed.data;
  } catch {
    return null;
  }
}

function writeLiveCache(profile: LiveProfile) {
  try {
    window.localStorage.setItem(
      LIVE_CACHE_KEY,
      JSON.stringify({ fetchedAt: Date.now(), data: profile }),
    );
  } catch {
    // storage unavailable — skip caching, fetch again next visit
  }
}

/**
 * Fetches the live GitHub profile in the browser so the portrait and
 * availability status update on their own when GitHub data changes —
 * no rebuild or deploy required. The GitHub REST API is CORS-open for
 * public data. Responses are cached in localStorage for a short TTL to
 * stay comfortably inside the anonymous rate limit (60 requests/hour/IP).
 * Falls back to the last cached response (or null) if the API is unreachable.
 */
export async function fetchLiveProfile(): Promise<LiveProfile | null> {
  const cached = readLiveCache();
  const login = data.profile?.login ?? "geduful";
  try {
    const res = await fetch(`https://api.github.com/users/${login}`, {
      headers: { Accept: "application/vnd.github+json" },
      cache: "no-store",
    });
    if (!res.ok) return cached;
    const json = (await res.json()) as {
      name?: string | null;
      avatar_url?: string | null;
      hireable?: boolean | null;
      location?: string | null;
    };
    const live: LiveProfile = {
      name: json.name ?? null,
      avatarUrl: json.avatar_url ?? null,
      hireable: json.hireable ?? null,
      location: json.location ?? null,
    };
    writeLiveCache(live);
    return live;
  } catch {
    return cached;
  }
}

export type LiveReposResult = {
  repos: GithubRepo[];
  /** "live" = confirmed fresh from the API (200 or 304), "cache" = stale/offline fallback. */
  source: "live" | "cache";
  /** Epoch ms when this data was last confirmed fresh. */
  updatedAt: number;
};

const LIVE_REPOS_CACHE_KEY = "github-live-repos";
const LIVE_REPOS_TTL_MS = 30 * 60 * 1000;

type LiveReposCache = {
  fetchedAt: number;
  etag: string | null;
  repos: GithubRepo[];
};

function readLiveReposCache(): LiveReposCache | null {
  try {
    const item = window.localStorage.getItem(LIVE_REPOS_CACHE_KEY);
    if (!item) return null;
    const parsed = JSON.parse(item) as Partial<LiveReposCache>;
    if (
      typeof parsed.fetchedAt !== "number" ||
      !Array.isArray(parsed.repos) ||
      !parsed.repos.every((repo) => typeof repo?.name === "string")
    ) {
      return null;
    }
    return {
      fetchedAt: parsed.fetchedAt,
      etag: typeof parsed.etag === "string" ? parsed.etag : null,
      repos: parsed.repos as GithubRepo[],
    };
  } catch {
    return null;
  }
}

function writeLiveReposCache(cache: LiveReposCache) {
  try {
    window.localStorage.setItem(LIVE_REPOS_CACHE_KEY, JSON.stringify(cache));
  } catch {
    // storage unavailable — skip caching, fetch again next visit
  }
}

function toGithubRepo(repo: {
  name?: string;
  description?: string | null;
  html_url?: string | null;
  homepage?: string | null;
  language?: string | null;
  topics?: string[];
  pushed_at?: string | null;
}): GithubRepo | null {
  if (!repo.name) return null;
  return {
    name: repo.name,
    description: repo.description ?? null,
    htmlUrl: repo.html_url ?? null,
    homepage: repo.homepage ?? null,
    language: repo.language ?? null,
    topics: repo.topics ?? [],
    pushedAt: repo.pushed_at ?? null,
  };
}

/**
 * Fetches the live repository list in the browser so newly pushed projects
 * appear on the portfolio with no rebuild or deploy. Uses ETag conditional
 * requests — a `304 Not Modified` response confirms freshness without
 * counting against the anonymous rate limit (60 requests/hour/IP).
 * Results are cached in localStorage for 30 minutes; when the API is
 * unreachable the last cached list is returned instead.
 */
export async function fetchLiveRepos(): Promise<LiveReposResult | null> {
  const cached = readLiveReposCache();
  if (cached && Date.now() - cached.fetchedAt < LIVE_REPOS_TTL_MS) {
    return { repos: cached.repos, source: "cache", updatedAt: cached.fetchedAt };
  }

  const login = data.profile?.login ?? "geduful";
  try {
    const res = await fetch(
      `https://api.github.com/users/${login}/repos?per_page=100&sort=pushed`,
      {
        headers: {
          Accept: "application/vnd.github+json",
          ...(cached?.etag ? { "If-None-Match": cached.etag } : {}),
        },
        cache: "no-store",
      },
    );
    if (res.status === 304 && cached) {
      const touched = { ...cached, fetchedAt: Date.now() };
      writeLiveReposCache(touched);
      return { repos: cached.repos, source: "live", updatedAt: touched.fetchedAt };
    }
    if (!res.ok) {
      return cached
        ? { repos: cached.repos, source: "cache", updatedAt: cached.fetchedAt }
        : null;
    }
    const json = (await res.json()) as Array<{
      name?: string;
      fork?: boolean;
      description?: string | null;
      html_url?: string | null;
      homepage?: string | null;
      language?: string | null;
      topics?: string[];
      pushed_at?: string | null;
    }>;
    const repos = json
      .filter((repo) => !repo.fork)
      .map(toGithubRepo)
      .filter((repo): repo is GithubRepo => repo !== null);
    const fresh: LiveReposCache = {
      fetchedAt: Date.now(),
      etag: res.headers.get("etag"),
      repos,
    };
    writeLiveReposCache(fresh);
    return { repos, source: "live", updatedAt: fresh.fetchedAt };
  } catch {
    return cached
      ? { repos: cached.repos, source: "cache", updatedAt: cached.fetchedAt }
      : null;
  }
}
