import raw from "../data/generated/github.json";

/**
 * Typed accessor for the snapshot generated by `npm run sync`
 * (scripts/sync-github.mjs). The site reads live GitHub data through
 * this module and falls back to curated values where the API has no data.
 */

export type GithubProfile = {
  name?: string | null;
  login?: string | null;
  bio?: string | null;
  avatarUrl?: string | null;
  location?: string | null;
  hireable?: boolean | null;
  twitterUsername?: string | null;
  htmlUrl?: string | null;
};

export type GithubRepo = {
  name: string;
  description?: string | null;
  htmlUrl?: string | null;
  homepage?: string | null;
  language?: string | null;
  topics?: string[];
  pushedAt?: string | null;
};

export type GithubLanguageStat = {
  language: string;
  percent: number;
};

export type GithubData = {
  fetchedAt?: string;
  profile?: GithubProfile;
  repos?: GithubRepo[];
  repoLanguages?: GithubLanguageStat[];
};

const data = raw as unknown as GithubData;

export const github = {
  fetchedAt: data.fetchedAt ?? "",
  profile: data.profile ?? {},
  repos: data.repos ?? [],
  repoLanguages: data.repoLanguages ?? [],

  findRepo(name: string): GithubRepo | undefined {
    return this.repos.find((repo) => repo.name === name);
  },
};
