import raw from "../data/generated/github.json";

/**
 * Typed accessor for the snapshot generated by `npm run sync`
 * (scripts/sync-github.mjs). The site reads live GitHub data through
 * this module and falls back to curated values where the API has no data.
 */

export type GithubProfile = {
  name?: string | null;
  login?: string | null;
  bio?: string | null;
  avatarUrl?: string | null;
  location?: string | null;
  hireable?: boolean | null;
  twitterUsername?: string | null;
  htmlUrl?: string | null;
};

export type GithubRepo = {
  name: string;
  description?: string | null;
  htmlUrl?: string | null;
  homepage?: string | null;
  language?: string | null;
  topics?: string[];
  pushedAt?: string | null;
};

export type GithubLanguageStat = {
  language: string;
  percent: number;
};

export type GithubData = {
  fetchedAt?: string;
  profile?: GithubProfile;
  repos?: GithubRepo[];
  repoLanguages?: GithubLanguageStat[];
};

const data = raw as unknown as GithubData;

export const github = {
  fetchedAt: data.fetchedAt ?? "",
  profile: data.profile ?? {},
  repos: data.repos ?? [],
  repoLanguages: data.repoLanguages ?? [],

  findRepo(name: string): GithubRepo | undefined {
    return this.repos.find((repo) => repo.name === name);
  },
};

export type LiveProfile = {
  name: string | null;
  avatarUrl: string | null;
  hireable: boolean | null;
  location: string | null;
};

const LIVE_CACHE_KEY = "github-live-profile";
const LIVE_CACHE_TTL_MS = 15 * 60 * 1000;

function readLiveCache(): LiveProfile | null {
  try {
    const item = window.localStorage.getItem(LIVE_CACHE_KEY);
    if (!item) return null;
    const parsed = JSON.parse(item) as { fetchedAt: number; data: LiveProfile };
    if (Date.now() - parsed.fetchedAt > LIVE_CACHE_TTL_MS) return null;
    return parsed.data;
  } catch {
    return null;
  }
}

function writeLiveCache(profile: LiveProfile) {
  try {
    window.localStorage.setItem(
      LIVE_CACHE_KEY,
      JSON.stringify({ fetchedAt: Date.now(), data: profile }),
    );
  } catch {
    // storage unavailable — skip caching, fetch again next visit
  }
}

/**
 * Fetches the live GitHub profile in the browser so the portrait and
 * availability status update on their own when GitHub data changes —
 * no rebuild or deploy required. The GitHub REST API is CORS-open for
 * public data. Responses are cached in localStorage for a short TTL to
 * stay comfortably inside the anonymous rate limit (60 requests/hour/IP).
 * Falls back to the last cached response (or null) if the API is unreachable.
 */
export async function fetchLiveProfile(): Promise<LiveProfile | null> {
  const cached = readLiveCache();
  const login = data.profile?.login ?? "geduful";
  try {
    const res = await fetch(`https://api.github.com/users/${login}`, {
      headers: { Accept: "application/vnd.github+json" },
      cache: "no-store",
    });
    if (!res.ok) return cached;
    const json = (await res.json()) as {
      name?: string | null;
      avatar_url?: string | null;
      hireable?: boolean | null;
      location?: string | null;
    };
    const live: LiveProfile = {
      name: json.name ?? null,
      avatarUrl: json.avatar_url ?? null,
      hireable: json.hireable ?? null,
      location: json.location ?? null,
    };
    writeLiveCache(live);
    return live;
  } catch {
    return cached;
  }
}
